# Layers Rules  
layerrule = blur on, match:namespace rofi
layerrule = animation slide top, match:namespace logout_dialog
layerrule = animation slide down, match:namespace waybar
layerrule = animation fade 50%, match:namespace wallpaper
